### ISSUE TITLE
Updates toward UL

### ISSUE THREAD

**Issue by kpedro88** [TreeMaker/TreeMaker#571]
Step 1:

Samples:
- [x] Get list of UL backgrounds, data, etc.
- [x] Get file lists
- [x] Update production dictionaries for Condor submission
- [x] For samples w/ LO cross sections: rerun GenXsecAnalyzer or check xsdb
- [x] Get effective number of events (neff) for samples w/ negative weights

Object ID (update selections, working points, etc.):
- [x] PFJetID
- [x] Electron ID
- [x] Photon ID
- [x] Muon ID
- [x] b-tag discriminators, WPs
- [x] MET filters
- [x] PDF names

Corrections:
- [x] Scenarios, global tags for each year & type (data, MC, signal)
- [x] Golden JSON
- [x] Pileup JSON
- [x] JECs
- [x] JERs
- [x] Pileup reweighting
- [x] Prefiring

Content:
- [x] UL miniAOD branches
- [x] Forward-port various changes to older branches (signal-specific additions, etc.)
- [ ] Add file size checking script from @aperloff (& check uproot4 compatibility)
- [x] Ntuple event size: impact of AK15 jets, AK8 jets w/ no pt cut (reclustering), tracks, PF candidates (associated w/ tracks, associated w/ jets), SUEP needs (different jet cone sizes/algorithms, lower-pt tracks)
- [x] Ntuple processing speed w/ above additions (impact of reclustering, etc.)

Cleanup (items to remove):
- [x] "wrong pileup" identifier for MC samples
- [x] 80X processing options
- [x] 2017 MET fix
- [x] pre-UL: samples, unit tests, data files, Eras, scenarios, WeightProducer lines
- [ ] probably more

Step 2: ?

Step 3: Profit

**Comment by semrat** [comment]
Hi @kpedro88 @aperloff @cmadrid1 @JHiltbrand
**A. Here is the sample list to make the cff files and the condor dictionaries:**
**-----------------------------------------------------------------------------**
meta_dict = {  
        "ttbar"           : ['TTJets','TT_Tune','TTTo2L2Nu','TTToSemiLeptonic','TTToHadronic'],
        "tth"    : ['TTZTo','TTWJets','TTGJets','TTGamma','TTHH','TTTT','TTTW','TTWH','TTWW','TTWZ','TTZH','TTZZ','ttHJet'],
        "qcd"            : ['QCD_HT',],
        "qcd_pt"      : ['QCD_Pt',],
        "diboson"    : ['WGJets','WW','WZ','ZG','ZZ'],
        #"triboson" : ["WWW","WWZ","WZZ","ZZZ"],
        "dyjets"       : ['DYJetsToLL',],
        "wjets"        : ['WJetsToLNu',],
        "gjets"        : ['GJets',],
        "zjets"        : ['ZJetsToNuNu',],
        "signal"      : ['SMS','RPV','StealthSYY','StealthSHH'],
        "singlet"     : ['ST_s-channel','ST_t-channel','ST_tW','tZq'],
    }
**_Note that:_**
1. We got this list from TreeMaker/Production/test/condorSub/makeDicts.py 
2. Triboson samples are included by diboson
3. Also, RPV and Stealth signal UL central samples are not started yet to produce



**B. We also have a black list:**
**------------------------------**
blacklist = [
        "HT500Njet7", "mtop166p5",  "mtop169p5",  "mtop169p5",
        "mtop171p5",   "mtop171p5",   "mtop173p5",  "mtop175p5",
        "mtop178p5",  "widthx0p7",    "widthx0p85", "widthx0p85",
        "widthx1p15",  "widthx1p15",   "widthx1p3",   "widthx1p3",
        "Pilot",      "_0J_",         "_1J_",       "_2J_",
        "anomwtbLV",  "Polarization", "M-10to50"
    ]
**_Note that:_**
We ignore the samples which have these keywords as it seems they correspond to special version of certain samples

**Comment by kpedro88** [comment]
@semrat we also need to see the results of this meta-dictionary, i.e. all of the actual samples for which you made cff files so far.

**Comment by semrat** [comment]
Hi @kpedro88, here are whatever you want to see about the samples
I will update you asap I get the neff things

**Here are the commits to push the dictionaries and samples to gitHub:**
I pushed my changes to opened PR which made by Joshua: https://github.com/TreeMaker/TreeMaker/pull/573
1.  added cff dictionaries to get the root files corresponding to each sample for each year
     -- please look at **../test/dict_cff_Summer20UL16.py, dict_cff_Summer20UL16APV.py, dict_cff_Summer20UL17.py, dict_cff_Summer20UL18.py**

2. added the file lists which include the root files corresponding to each sample for each year
    -- please look at the **../python/_Summer20UL16, Summer20UL16APV, Summer20UL17, Summer20UL18_** directories

3. added the condor submit dictionaries
    -- please look at the **condorSub/ul_condorSubmit_dictionaries/**
    -- for now I want to keep them in a directory, after you check I will move them to condorSubmit/

Could you please, let me know if I make a mistake whenever I get the extended sample for both cff and condor submit dictionaries

Thank you from now on to review my progress 🤩 

**Note that:** We get all them above for only background samples for now, still need to get them also for data samples

**Comment by JHiltbrand** [comment]
Here is status checkpoint for UL updates [Updated: 20 September]:

**Get list of UL backgrounds, data, etc.**
- Latest and available Summer20UL samples have been added.

**Get file lists**
- As above, Summer20UL has been added to PR #573.

**Update production dictionaries for Condor submission**
-   Updated simultaneously with the samples and sample lists.

**For samples w/ LO cross sections: rerun GenXsecAnalyzer or check xsdb**
- Wrote a script to `curl` the xsdb and pull in all available xsections, then filled as many as I could with GenXsecAnalyzer where the samples exist. Conveniently, the the XS appears to be the same for all three years, which simplifies `MCSampleValues.py`. Added to our PR. _**Need to determine k-factors and still some samples not available yet.**_

**Get effective number of events (neff) for samples w/ negative weights**
- Was able to run on all amc@NLO samples for Summer20UL that are available and get the neff numbers, which will be integrated into the sample dictionaries. Added to the PR.
- 
**PFJetID**
- Updated with the latest recommended values.

**Electron ID**
- The electron ID appears to be good to go for UL, same recommendations as before. Recommended ID is 94X-v2 for all years. Effective areas used for miniIso remain the same as before for 94X.

**Photon ID**
- checked by @binayab and should be good to go.

**Muon ID**
- Verified the dB and dZ requirements carry into the UL era (contacted SUSY muon expert to confirm). Otherwise, muon ID is ready.

**b-tag discriminators, WPs**
- UL16 is still being worked on from what I see on the POG twiki, but UL17 and UL18 WPs are available. CSVv2 no longer has supported working points,  so it will be removed from the `makeJetVars.py`. WPs for DeepCSV will be integrated as well (changes to be pushed)

**MET filters**
- Only needed to add one additional filter for bad muon dZ. Likewise, the special rerunning for the two ECAL filters is no longer needed in UL and has been removed. Added noisy HF filter for those that want to use.

**PDF names**

 Corrections:

**Scenarios, global tags for each year & type (data, MC, signal)**
- Scenarios has been simplified and updated to just the UL versions (yet to be pushed). GTs are updated for each year as well.

**Golden JSON**
-  Golden JSON has been added in 212d0e8.

**Pileup JSON**
- Also added in 212d0e8

**JECs**
- Added in 212d0e8, though currently Summer19UL versions, Summer20UL versions are still being produced.

**JERs**
- Added in 212d0e8, though currently Summer19UL versions, Summer20UL versions are still being produced.

**Pileup reweighting**
- Current PileupHistogram ROOT files that had been pushed are not the correct files. We have the data PU distributions /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions{16,17,18}/13TeV/PileUp/UltraLegacy and can use `pileupCorr.py` to produce the weights histograms. For 2017, some large weights are observed in the last few nVtx bins. Did make a hypernews post, but no specific response about this observation for 2017.

**Prefiring**
- Added the muon prefiring to the ecal prefiring module and made it a generic prefiring module in e552f2b.

 Content:

**UL miniAOD branches**

**Ntuple event size: impact of AK15 jets, AK8 jets w/ no pt cut (reclustering), tracks, PF candidates (associated w/ tracks, associated w/ jets), SUEP needs (different jet cone sizes/algorithms, lower-pt tracks)**

**Ntuple processing speed w/ above additions (impact of reclustering, etc.)**


 Cleanup (items to remove):

**"wrong pileup" identifier for MC samples**
- Removed everywhere it is found.

**80X processing options**
- Removing everywhere as I find it.

**pre-UL: samples, unit tests, data files, Eras, scenarios, WeightProducer lines**
- Removing everywhere as I see them. I think I have removed most things related to legacy Run2.

**Comment by aperloff** [comment]
>     * An outstanding question, how to go about calculating k-factors ?

The k-factors are the (N)NLO theory or inclusive sample cross sections divided by the LO inclusive sample cross sections. So let's say we want to calculate the k-factor for `WJetsToLNu_HT-70To100` in 2016. The LO inclusive sample cross section is `50260` and the NNLO inclusive sample cross section is `61526.7`. Therefore the k-factor is `1.224`. From samples that are HT-binned, this usually means that the k-factors are the same within a given year.

**Comment by JHiltbrand** [comment]
> 
> 
> > ```
> > * An outstanding question, how to go about calculating k-factors ?
> > ```
> 
> The k-factors are the (N)NLO theory or inclusive sample cross sections divided by the LO inclusive sample cross sections. So let's say we want to calculate the k-factor for `WJetsToLNu_HT-70To100` in 2016. The LO inclusive sample cross section is `50260` and the NNLO inclusive sample cross section is `61526.7`. Therefore the k-factor is `1.224`. From samples that are HT-binned, this usually means that the k-factors are the same within a given year.

In the past, what did you guys typically do to get the xsec for the reference NLO or NNLO samples ? I guess there was this nice summary table [1], but I have not come across anything similar for UL yet.

[1] https://twiki.cern.ch/twiki/bin/viewauth/CMS/SummaryTable1G25ns

**Comment by aperloff** [comment]
> In the past, what did you guys typically do to get the xsec for the reference NLO or NNLO samples ? I guess there was this nice summary table [1], but I have not come across anything similar for UL yet.
> 
> [1] https://twiki.cern.ch/twiki/bin/viewauth/CMS/SummaryTable1G25ns

It says in the [dictionary holding the values](https://github.com/TreeMaker/TreeMaker/blob/Run2_2017/WeightProducer/python/MCSampleValues.py#L295) where they come from. For example, both the NNLO and LO cross section for WJets comes from the XSDB. For TTJets in 2016 the values both came from XSDB, but in 2017 and 2018 the LO value came from the GenXSecAnalyzer.

**Comment by kpedro88** [comment]
MET filters: we should probably add a branch for the new `hfNoisyHitsFilter` even if it's not recommended by default (https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#2018_2017_data_and_MC_UL)

Pileup reweighting:
* please record the exact `pileupCorr.py` commands used to produce the files either here or in the PR
* regarding the high weights for high PU: can we compare our files to the ones in `/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/UltraLegacy/`? I'm surprised that UL MC would be generated with an inadequate pileup distribution. We may need to follow up with the Lumi POG about this.

**Comment by JHiltbrand** [comment]
> 
> 
> MET filters: we should probably add a branch for the new `hfNoisyHitsFilter` even if it's not recommended by default (https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#2018_2017_data_and_MC_UL)

Sounds good. For the `BadChargedCandidateFilter` and `BadPFMuonFilter`, which are not taken directly from the TriggerResults [1], is that a result of their not being in the trigger results at the time ? It seems they are now, so should they be taken from the TriggerResults going forward or just leave it as is ?

[1] https://github.com/TreeMaker/TreeMaker/blob/007f2b8dba23073bc6dfa63c18a6f68063f599c7/TreeMaker/python/makeTreeFromMiniAOD_cff.py#L539-L551

**Comment by kpedro88** [comment]
Yes, originally they weren't available in miniAOD, so we reran them. (Then later it turned out that rerunning them on top of miniAOD avoided some bug/issue in the AOD version, so we kept doing it.) In UL, we should take the central TriggerResults versions.

**Comment by JHiltbrand** [comment]
>
> Pileup reweighting:
> 
>     * please record the exact `pileupCorr.py` commands used to produce the files either here or in the PR
> 
>     * regarding the high weights for high PU: can we compare our files to the ones in `/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/UltraLegacy/`? I'm surprised that UL MC would be generated with an inadequate pileup distribution. We may need to follow up with the Lumi POG about this.

The command I ran was:

```
python pileupCorr.py --latest data/pileup_latest_${year}.txt --data data/PileupHistogram-goldenJSON-13tev-${year}-69200ub-99bins.root --nbins 99 --minbias 69200 --scenario SimGeneral.MixingModule.mix_${year}_25ns_UltraLegacy_PoissonOOTPU_cfi --outname PileupHistograms_UL${year}_69mb_pm5.root
```

The ROOT and txt file(s) I provide to the `--data` and `--latest` options, respectively, were taken from the `/afs/` path you describe for the three years.

**Comment by aperloff** [comment]
> Ntuple event size: impact of AK15 jets, AK8 jets w/ no pt cut (reclustering), tracks, PF candidates (associated w/ tracks, associated w/ jets), SUEP needs (different jet cone sizes/algorithms, lower-pt tracks)

I have updated https://github.com/aperloff/utilities/blob/master/ROOT/AnalyzeTFileSizes.py to work with Python 3 (`3.6.8` to be specific) and uproot `v4.1.3`. I will note that in CMSSW_12_1_0_pre3 Python 3.9.6 the default version of uproot is still `v3.13.0` and the version of uproot4 is `v0.1.2`. So you will need some other way to access uproot in order to work with this new version of AnalyzeTFileSizes.py. I used a virtual environment:
```bash
python3 -m venv venv
source venv/bin/activate
pip install uproot
```
Note, however, that this does not include the XRootD python bindings, which are a pain to install without conda. Without the XRootD bindings you can only work with local files. With them, you should be able to access files via XRootD.
