### ISSUE TITLE
AK15 NSubJetiness 4

### ISSUE THREAD

**Issue by kapsiak** [TreeMaker/TreeMaker#650]
Hello,

For one of our analyses, we are looking to use higher order NSubJetiness (tau) variables for AK15 jets. 
Would it be possible to ass NSubJetiness 4 (Tau_4) for the AK15 jet collection? 

Thank you.

**Comment by kpedro88** [comment]
For what samples do you need this?

**Comment by kapsiak** [comment]
The major backgrounds for the model are TT and QCD, with a bit of weak stuff. 
Ideally then TT+Jets, TT+X,  QCD, and W+Jets.

**Comment by kpedro88** [comment]
We already have AK15 jets for TTJets (madgraph), QCD (both pythia and madgraph), and W+Jets, so adding one extra branch to those is hopefully not a big deal. (At least in terms of disk space; we need to assess how slow it is to compute Nsubjettiness tau_4.)

We do not have AK15 jets for TT (Powheg) or TT+X (which is a lot of processes). This implies substantial costs in both CPU time and disk space, the latter of which we really cannot afford right now.

Since this seems like an exploratory study at the moment, rather than tying this together with other ntuple updates that are more immediately pertinent for ongoing analyses, I suggest you privately reprocess small amounts of your samples of interest to understand what you actually need. You can use the following branch: https://github.com/kpedro88/TreeMaker/tree/Tau4. Be sure to include the argument `tchannel=True` to enable AK15 jets.

**Comment by kpedro88** [comment]
Computing tau_4 seems to be reasonably fast (adds a few seconds to the processing of 5K events).

**Comment by kapsiak** [comment]
Sounds good. To confirm, can we add tau_4 for the samples where AK15 jets are already produced?

**Comment by kpedro88** [comment]
Yes, see #654

**Comment by kapsiak** [comment]
Looks good, thank you
